--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: train-schedule
  name: train-schedule-deployment
spec: 
  replicas: 2
  selector: 
    matchLabels: 
      app: train-schedule
      track: stable
  template: 
    metadata: 
      labels: 
        app: train-schedule
        track: stable
    spec: 
      containers: 
        - 
          image: "$DOCKER_IMAGE_NAME:$BUILD_NUMBER"
          livenessProbe: 
            httpGet: 
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 1
          name: train-schedule
          ports: 
            - 
              containerPort: 8080
          resources: 
            requests: 
              cpu: 200m
